# fly.toml app configuration file for courtreserve-bot
# See https://fly.io/docs/reference/configuration/

app = 'courtreserve-bot'
primary_region = 'iad'

[build]

[env]
  HEADLESS = "true"

# Persistent storage for user credentials database
[mounts]
  source = "courtbot_data"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
